### PR TITLE
Upgrade vagrant to the latest as per the Orchestrator

### PR DESCRIPTION
**Pull request by patelswapnil**
This PR upgrades the vagrant environment of `kueui` to the latest as per the Orchestrator to benefit from consistence development environment.

### Set up

 - Destroy the current VM
 - Remove following entries from `/etc/hosts` file from your local machine:
   - 192.168.11.23:6001/api
   - 192.168.11.23:6001/kue

### To verify

 - [x] spin up the new VM instance: `vagrant up --provider=virtualbox`

 - [x] Vagrant has successfully created VM for `kueui`

 - [x] `v ssh`

- [ ] Execute `c npm all install`

 - [x] build and run docker containers to test `kueui` application is up and running: 
    - Log into docker with `docker login -u <username>`
    - `c pull && c build`
    - `c up && c logs`

 - [ ] Access `kueui.repcoservice.local:6001/api` OR `kueui.repcoservice.local:6001/kue` to ensure `kueui` is up and running.

### CODE REVIEW

**Comment by patelswapnil** [comment]
@smebberson , A PR has been created for you to review the upgrade of vagrant environment in KUEUI as per Orchestrator.

**Review by smebberson — CHANGES_REQUESTED** [review]
When you run `c up && c logs` you get `WARNING: --all flag is obsolete. This is now the default behavior of `docker-compose rm`. Can you please update the `c` script so it better conforms with the new version of `docker-compose`... thanks.

**Comment by patelswapnil** [comment]
@smebberson this PR is ready for follow up review.

**Comment by patelswapnil** [comment]
@smebberson, all tidy up suggestions are done. This PR is ready for follow up review.

**Review by smebberson — APPROVED** [review]

**Pull request merged**
